

AREA_DEFINITION_WORKSHEET =  "NSW Area Definitions"
ZONE_DEFINITION_WORKSHEET = "NSW Zone Definitions"
RATES_WORKSHEET = "NSW_Rates"

ORDER_REPORT_WORKSHEET = "Order Report"

CUSTOMER = 'CUSTOMER'
REGION = "REGION"
INVOICE_ID = 'INVOICE NO'
AMT_INCL_TAX = 'AMOUNT INCL TAX'
AMT_EXL_TAX = 'AMOUNT EXCL TAX'
CONSIGNMENT_ID = 'CONSIGNMENT ID'
ARTICLE_ID = 'ARTICLE ID'
FROM_STATE = 'FROM STATE'
FROM_POSTAL_CODE = 'FROM POSTAL CODE'
TO_STATE = 'TO STATE'
TO_POSTAL_CODE = 'TO POSTAL CODE'
BILLING_DATE = 'BILLING DATE'
BILLED_WEIGHT = 'BILLED WEIGHT'
CAL_INCL_TAX = "CAL INCL TAX"
CAL_EXCL_TAX = "CAL EXCL TAX"
DESCRIPTION = "DESCRIPTION"
IS_INCL_MATCHED = "INCL MATCHED"
IS_EXCL_MATCHED = "EXCL MATCHED"
ARTICLE_ID_MATCHED = "ARTICLE_ID_MATCHED"

ARTICLE_ID_NOT_FOUND = "Article Id not found"